apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: block-nodeport-services
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constrainttemplates/block-nodeport-services.yaml
    options: {}
    type: Yaml

