apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: container-resource-ratios
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constraints/container-resource-ratios.yaml
    options: {}
    type: Yaml
  templateName: container-resource-ratios