apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: disallowed-tags
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constraints/disallowed-tags.yaml
    options: {}
    type: Yaml
  templateName: disallowed-tags