apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: sstest
  project: defaultproject
spec:
  base:
    name: default
    version: 1.13.0
  defaultAddons:
    enableIngress: false
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  version: v3
