apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: host-namespace-custom
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constraints/host-namespace.yaml
    options: {}
    type: Yaml
  templateName: host-namespace-custom