apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: container-resource-ratios
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constrainttemplates/container-resource-ratios.yaml
    options: {}
    type: Yaml

