apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: block-nodeport-services
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constraints/block-nodeport-services.yaml
    options: {}
    type: Yaml
  templateName: block-nodeport-services