apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: replica-limits
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://constraints/replica-limits.yaml
    options: {}
    type: Yaml
  templateName: replica-limits