apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx2
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: nginx
  placement: {}
