apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/nginx/nginx.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: nginx
  placement:
    selector: rafay.dev/clusterName=opa-testing
  version: nginx-v9
